---

- name: keypair deploy
  hosts: all
  gather_facts: false
  ignore_errors: true
  tasks:

  - name: authorized_keys delete
    file:
      path: /root/.ssh/authorized_keys
      state: absent
    tags: step1

  - name: authorized_keys create
    file:
      path: /root/.ssh/authorized_keys
      state: touch
    tags: step2

  - name: put public key
    lineinfile:
      path: /root/.ssh/authorized_keys
      line: "{{ pubkey }}"
    tags: step3
