---
- name: Wordpress Install & Configuration
  hosts: web
  gather_facts: false
  ignore_errors: true

  tasks:
  - name: yum install http
    yum:
      name: httpd
      state: present

  - name: amzn2 enable php7.2
    shell: 'amazon-linux-extras enable php7.2 lamp-mariadb10.2-php7.2'

  - name: yum install php* mariadb
    yum:
      name:
        - php-cli
        - php-pdo
        - php-fpm
        - php-json
        - php-mysqlnd
        - mariadb
        - php
      state: present

  - name: get_url wordpress
    get_url:
      url: 'https://ko.wordpress.org/latest-ko_KR.tar.gz'
      dest: './'

  - name: unarchive
    unarchive:
      src: './wordpress-5.8.2-ko_KR.tar.gz'
      dest: './'
      remote_src: yes

  - name: wordpress file copy dest /var/www/html
    copy:
      src: './wordpress/*'
      dest: '/var/www/html/'
      remote_src: yes

  - name: chown
    file:
      path: '/var/www/html/*'
      owner: apache
      group: apache

  - name: file copy wp-config.php
    copy:
      src: '/var/www/html/wp-config-sample.php'
      dest: '/var/www/html/wp-config.php'
      remote_src: yes

  - name: change syntax DirectoryIndex
    replace:
      path: '/etc/httpd/conf/httpd.conf'
      regexp: 'DirectoryIndex index.html'
      replace: 'DirectoryIndex index.php'

  - name: change syntax database_name_here
    replace:
      path: '/var/www/html/wp-config.php'
      regexp: 'database_name_here'
      replace: 'mydb'

  - name: change syntax username_here
    replace:
      path: '/var/www/html/wp-config.php'
      regexp: 'username_here'
      replace: 'admin'

  - name: change syntax password_here
    replace:
      path: '/var/www/html/wp-config.php'
      regexp: 'password_here'
      replace: 'It12345!'

  - name: change syntax localhost
    replace:
      path: '/var/www/html/wp-config.php'
      regexp: 'localhost'
      replace: 'mydb.cqep7uwq9udb.ap-northeast-2.rds.amazonaws.com'

  - name: make file
    file:
      path: '/var/www/html/health.html'
      state: touch

  - name: copy contents
    copy:
      content: |
        <html>
        <body>
        <h1>SDKIM_WEBSERVER-1</h1>
        </body>
        <html>
      dest: '/var/www/html/health.html'

  - name: systemctl start httpd & systemctl enable httpd
    systemd:
      name: httpd
      state: started
      enabled: yes

